### ISSUE TITLE
Route [index] not defined.

### ISSUE THREAD

**Issue by ArtMin96** [hexters/ladmin#11]
I don't know why but there is a lot of problems with routes first able. After clean laravel installation Datatables do not exist, routes not defined.

**Comment by hexters** [comment]
Open your DataTables server file in `app/Datatables/` folder and find `'ajax' => route('index')` change `route('index')` to your controller or route for handle Datatables list.

Example in `app/Datatables/PermissionDatatables.php` file
```
. . .

'options' => [
          'topButton' => null,
          'processing' => true,
              'serverSide' => true,
              'ajax' => route('administrator.access.permission.index'), // <--- your problem here
              'columns' => [
                  ['data' => 'id', 'class' => 'text-center'],
                  ['data' => 'name'],
                  ['data' => 'action', 'class' => 'text-center', 'orderable' => false]
              ]
        ]
 
. . .
```
