### ISSUE TITLE
Error when accessing log

### ISSUE THREAD

**Issue by hendisantika** [hexters/ladmin#12]
Nice repo.
But, I have error when accessing log

`http://localhost:8000/administrator/system/log`

![image](https://user-images.githubusercontent.com/3713580/99895356-a80e9800-2cba-11eb-9e83-4eea04c1b5ce.png)

Any advice?

Thanks

**Comment by hexters** [comment]
Your file is too large

**Comment by hendisantika** [comment]
Kegedean kmh kang?
Pan eta ieu mah nembe g nginstal atuh.
