### ISSUE TITLE
Notification related error

### ISSUE THREAD

**Issue by Saad-Malik** [hexters/ladmin#20]
I was using the admin panel, it was working fine. I update the composer and now it gives me this error 

lluminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'notifications.notifiable_id' in 'where clause' (SQL: select * from `notifications` where `notifications`.`notifiable_id` = 1 and `notifications`.`notifiable_id` is not null and `notifications`.`notifiable_type` = App\Models\User and `read_at` is null order by `created_at` desc, `created_at` desc limit 10) (View: views\layouts\app.blade.php)

**Comment by Saad-Malik** [comment]
Oh okay, I found the answer. I needed to do PHP artisan notifications:table and migrate it later. It solved my issue.

**Comment by hexters** [comment]
Hi thanks for using Ladmin package

Please read thid https://github.com/hexters/ladmin/releases/tag/v1.8.0
You need to create notification table php artisan notifications:table
 I have change the datatables class structure check this
https://github.com/hexters/ladmin/blob/master/stubs/Datatables.stub

And please read again the documentation in readme.md

😀

Pada tanggal Sen, 11 Jan 2021 pukul 06.14 Saad Malik <
notifications@github.com> menulis:

**Comment by Saad-Malik** [comment]
Yes I noticed. You also make changes in the data table structure as well :D 
I will look into change documentation. Thanks for the share.

**Comment by hexters** [comment]
If there are still errors, I suggest you keep using the last version of
1.7. *

Pada tanggal Sen, 11 Jan 2021 pukul 06.41 Asep Saepuloh Sahidin <
hexters@gmail.com> menulis:

**Comment by Saad-Malik** [comment]
I only faced the issue with the notification. Rest I had to change my data table structure because I was getting a particular error regarding the htmlspecialchars().
