### ISSUE TITLE
Laravel 9 || syntax error, unexpected ':', expecting ')' || vendor/hexters/ladmin/src/Helpers/Ladmin.php

### ISSUE THREAD

**Issue by hendrix37** [hexters/ladmin#39]
`Nothing to install, update or remove
6 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   ParseError 

  syntax error, unexpected ':', expecting ')'

  at vendor/hexters/ladmin/src/Helpers/Ladmin.php:92
     88▕      * @return void
     89▕      */
     90▕     public function view($blade, $data = [])
     91▕     {
  ➜  92▕         return view($this->view_path(blade: $blade), $data);
     93▕     }
     94▕ 
     95▕     /**
     96▕      * Load ladmin template

      +1 vendor frames 
  2   [internal]:0
      Composer\Autoload\ClassLoader::loadClass()

      +9 vendor frames 
  12  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
`

if i do install this packages show this error

**Comment by hexters** [comment]
Please use min php 8.0
