### ISSUE TITLE
syntax error, unexpected ':', expecting ')'

### ISSUE THREAD

**Issue by Gugun09** [hexters/ladmin#40]
![Screenshot_32](https://user-images.githubusercontent.com/54890927/161441696-6ba6f16f-1d31-4a9a-ac18-eb617c0f9883.jpg)

**Comment by hexters** [comment]
It features **Named Arguments** from php 8.0, make sure the version you are using is min php 8.0 and laravel 9.

## Reference Link
https://php.watch/versions/8.0/named-parameters
