### ISSUE TITLE
Error on Publishing

### ISSUE THREAD

**Issue by catwhocode** [hexters/ladmin#45]
:: after doing migration on laravel fresh install ::

when running 

`php artisan ladmin:install --and=ladmin:setup`

it throw this error

```
In Application.php line 827:
  Class "Modules\Ladmin\Providers\LadminServiceProvider" not found
```

:: Laravel 10.10 fresh install on PHP 8.1.6 ::

**Comment by hexters** [comment]
Hi @catwhocode thank for using this package, try running the `composer dumpautoload` command.
