### ISSUE TITLE
Class "Hexters\Ladmin\Supports\BaseMenu" not found

### ISSUE THREAD

**Issue by erdowaka** [hexters/ladmin#49]
Pagi Kak, ladmin nya keren nih, cuma mau tanya kenapa saat saya tambahin untuk menu storage muncul errornya yah ? saya pun heran padahl udah ngikutin yang di module untuk tambah data 

![image](https://github.com/hexters/ladmin/assets/32562893/aa00a4bc-c074-4ef2-9c36-4a301d7bc7c0)

**Comment by hexters** [comment]
Terimakasih telah menggunakan Ladmin, support ladmin storage saat ini hanya untuk versi ladmin 2
