### ISSUE TITLE
Ladmin halaman utama

### ISSUE THREAD

**Issue by DandyBagusPrasetyo** [hexters/ladmin#9]
Bang, mau nanya caranya biar vendor ladmin ini jadi tampilan utama di route / gimana ya? Jadi gk perlu localhost:8080/administrator lagi. Langsung localhost:8080/

**Comment by hexters** [comment]
Di redirect aja dari :8000/ ke :8000/administrator


Prefix Admistrator nya bisa di rename jadi admin misal biar pendek.

Lihat file config.

**Comment by guepejuang** [comment]
cara masukin route ladmin ke web.php gmn bang? sy udah ikutin tutor pas akses ke /administrator 404. atau ada step yg tertinggal?
